Traceback (most recent call last):
  File "/Users/kennyzhu/Documents/dataVizz-Jbook/.venv/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/kennyzhu/Documents/dataVizz-Jbook/.venv/lib/python3.11/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kennyzhu/Documents/dataVizz-Jbook/.venv/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/kennyzhu/Documents/dataVizz-Jbook/.venv/lib/python3.11/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/kennyzhu/Documents/dataVizz-Jbook/.venv/lib/python3.11/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/kennyzhu/Documents/dataVizz-Jbook/.venv/lib/python3.11/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
from scipy.stats import zscore, t
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer, IterativeImputer
from sklearn.model_selection import cross_val_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import HistGradientBoostingClassifier, StackingClassifier, BaggingClassifier, VotingClassifier
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
Cell [0;32mIn[1], line 12[0m
[1;32m     10[0m [38;5;28;01mimport[39;00m [38;5;21;01mseaborn[39;00m [38;5;28;01mas[39;00m [38;5;21;01msns[39;00m
[1;32m     11[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[0;32m---> 12[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mimpute[39;00m [38;5;28;01mimport[39;00m SimpleImputer, IterativeImputer
[1;32m     13[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mmodel_selection[39;00m [38;5;28;01mimport[39;00m cross_val_score
[1;32m     14[0m [38;5;28;01mfrom[39;00m [38;5;21;01msklearn[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpipeline[39;00m [38;5;28;01mimport[39;00m make_pipeline

File [0;32m~/Documents/dataVizz-Jbook/.venv/lib/python3.11/site-packages/sklearn/impute/__init__.py:18[0m, in [0;36m__getattr__[0;34m(name)[0m
[1;32m     16[0m [38;5;28;01mdef[39;00m [38;5;21m__getattr__[39m(name):
[1;32m     17[0m     [38;5;28;01mif[39;00m name [38;5;241m==[39m [38;5;124m"[39m[38;5;124mIterativeImputer[39m[38;5;124m"[39m:
[0;32m---> 18[0m         [38;5;28;01mraise[39;00m [38;5;167;01mImportError[39;00m(
[1;32m     19[0m             [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00mname[38;5;132;01m}[39;00m[38;5;124m is experimental and the API might change without any [39m[38;5;124m"[39m
[1;32m     20[0m             [38;5;124m"[39m[38;5;124mdeprecation cycle. To use it, you need to explicitly import [39m[38;5;124m"[39m
[1;32m     21[0m             [38;5;124m"[39m[38;5;124menable_iterative_imputer:[39m[38;5;130;01m\n[39;00m[38;5;124m"[39m
[1;32m     22[0m             [38;5;124m"[39m[38;5;124mfrom sklearn.experimental import enable_iterative_imputer[39m[38;5;124m"[39m
[1;32m     23[0m         )
[1;32m     24[0m     [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mmodule [39m[38;5;132;01m{[39;00m[38;5;18m__name__[39m[38;5;132;01m}[39;00m[38;5;124m has no attribute [39m[38;5;132;01m{[39;00mname[38;5;132;01m}[39;00m[38;5;124m"[39m)

[0;31mImportError[0m: IterativeImputer is experimental and the API might change without any deprecation cycle. To use it, you need to explicitly import enable_iterative_imputer:
from sklearn.experimental import enable_iterative_imputer

